import { Command } from "commander";
import chalk from "chalk";
import ora from "ora";
import fs from "fs-extra";
import path from "path";
import { fileURLToPath } from "url";

// Note: We need to go up TWO levels from src/cli/commands to src/api
import OAuthClient from "../../api/OAuthClient.js";
import ConverterEngine from "../../converters/index.js";
import GasParser from "../../analyzer/GasParser.js";
import ProjectGenerator from "../../generators/ProjectGenerator.js";
import ExpoProjectGenerator from "../../generators/ExpoProjectGenerator.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename); // eslint-disable-line no-unused-vars

// Helper function to generate project structure
async function generateProjectStructure(outputDir, frameworks, _analysis) {
  console.log(chalk.blue("ðŸ—ï¸ Generating project files..."));
  
  try {
    const projectGenerator = new ProjectGenerator();
    
    const result = await projectGenerator.generateProject(
      path.basename(outputDir),
      {
        frameworks,
        database: "postgres", // TODO: Make this configurable
        outputDir: path.dirname(outputDir),
        demoMode: false,
      }
    );
    
    if (result.success) {
      console.log(chalk.green(`âœ… Project structure created with ${result.files} files`));
    } else {
      console.error(chalk.red("âŒ Failed to generate project structure: "), result.error);
    }
  } catch (error) {
    console.error(chalk.red("âŒ Error generating project structure: "), error.message);
  }
}

// Helper function to generate Expo project structure
async function generateExpoProjectStructure(outputDir, frameworks, options) {
  console.log(chalk.blue("ðŸ“± Generating Expo mobile app..."));
  
  try {
    const expoProjectGenerator = new ExpoProjectGenerator();
    
    const result = await expoProjectGenerator.generateExpoProject(
      path.basename(outputDir),
      {
        outputDir: path.dirname(outputDir),
        apiUrl: options.apiUrl || "http://localhost:3000",
        includeWeb: true,
        platforms: ["ios", "android", "web"],
        features: ["api", "navigation", "offline"],
      }
    );
    
    if (result.success) {
      console.log(chalk.green(`âœ… Expo project created with ${result.platforms.join(", ")} support`));
      
      // Generate a mobile-specific migration report
      await generateMobileMigrationReport(outputDir, options);
    } else {
      console.error(chalk.red("âŒ Failed to generate Expo project: "), result.error);
    }
  } catch (error) {
    console.error(chalk.red("âŒ Error generating Expo project: "), error.message);
  }
}

// Helper function to generate mobile migration report
async function generateMobileMigrationReport(outputDir, analysis) {
  const report = `# Expo Mobile App Migration Report

## Project Details
- **Generated**: ${new Date().toISOString()}
- **Platforms**: iOS, Android, Web
- **Backend API**: ${analysis.apiUrl || "http://localhost:3000"}
- **Demo Mode**: ${analysis.demo ? "Yes" : "No"}

## Generated Structure
\`\`\`
${outputDir}/
â”œâ”€â”€ app/                    # Expo Router (File-based routing)
â”œâ”€â”€ components/            # Reusable components
â”œâ”€â”€ screens/              # Screen components
â”œâ”€â”€ services/             # API services
â”œâ”€â”€ assets/               # Images, fonts, icons
â”œâ”€â”€ app.json              # Expo configuration
â””â”€â”€ package.json          # Dependencies
\`\`\`

## Setup Instructions

### 1. Install Dependencies
\`\`\`bash
cd ${outputDir}
npm install
\`\`\`

### 2. Start Development
\`\`\`bash
# Start all platforms
npm start

# Platform specific
npm run android    # Android
npm run ios        # iOS
npm run web        # Web
\`\`\`

### 3. Connect to Backend
Ensure your Express.js backend is running at:
\`${analysis.apiUrl || "http://localhost:3000"}\`

## Testing

### On Device:
1. Install Expo Go app on your phone
2. Scan QR code from terminal
3. App loads instantly on device

### On Emulator:
1. Set up Android/iOS emulator
2. Run platform-specific command
3. App launches in emulator

## Building for Production

### Android (APK):
\`\`\`bash
npm run build:android
\`\`\`

### iOS (IPA):
\`\`\`bash
npm run build:ios
\`\`\`

## Features Included

âœ… **Expo Router** - File-based navigation
âœ… **API Integration** - Pre-configured GAS API client
âœ… **Offline Support** - AsyncStorage persistence
âœ… **Cross-Platform** - iOS, Android, Web  
âœ… **TypeScript Ready** - Add types as needed
âœ… **EAS Build** - Expo Application Services

## Next Steps

1. Update \`.env.example\` â†’ \`.env\` with your API URL
2. Customize UI in \`app/\` directory
3. Test API connectivity
4. Deploy to app stores

## Support

For mobile-specific issues:
- Check Expo documentation
- Verify API CORS settings
- Ensure backend is accessible from mobile

*Generated by CÂ³X CLI - Dual Platform Migration*`;
  
  await fs.writeFile(path.join(outputDir, "MOBILE_MIGRATION_REPORT.md"), report, "utf8");
}

// Helper function to generate migration report
async function generateMigrationReport(outputDir, analysis, _projectData) {
  const report = `# CÂ³X Migration Report

## Project Analysis
- **Project ID**: ${analysis.scriptId || "Unknown"}
- **Files Count**: ${analysis.fileCount || 0}
- **Complexity**: ${analysis.estimatedComplexity || "Unknown"}
- **Triggers**: ${analysis.triggers || 0}
- **Deployments**: ${analysis.deployments || 0}

## Migration Summary
- **Date**: ${new Date().toISOString()}
- **Status**: Completed successfully
- **Output Directory**: ${outputDir}

## Conversion Details
${analysis.demo ? "**NOTE: This was a demo migration. Real Google API integration was not used.**" : ""}

### Frameworks Applied:
1. **GUAPO**: Converted ${analysis.apiEndpoints || 0} API endpoints to Express.js
2. **GENIO**: Converted ${analysis.triggers || 0} triggers to Bull queues
3. **CHIEW**: Converted ${analysis.htmlFiles || 0} HTML files to React components

## Generated Structure
\`\`\`
${outputDir}/
â”œâ”€â”€ src/api/           # Express.js backend
â”œâ”€â”€ src/workers/       # Background job queues
â”œâ”€â”€ src/ui/           # React frontend
â”œâ”€â”€ database/         # Database migrations
â”œâ”€â”€ docker-compose.yml # Docker configuration
â””â”€â”€ README.md         # Project documentation
\`\`\`

## Next Steps
1. Review the migrated code
2. Install dependencies: \`cd ${outputDir} && npm install\`
3. Start development server: \`npm run dev\`
4. Deploy to your preferred platform

## Notes
This migration was performed by CÂ³X CLI.
For issues or feedback, visit our documentation.

## Support
If you encounter issues:
1. Check the generated code for TODO comments
2. Review the conversion patterns
3. Consult the CÂ³X documentation
4. Reach out to the CÂ³X community`;
  
  await fs.writeFile(path.join(outputDir, "MIGRATION_REPORT.md"), report, "utf8");
}

const migrateCommand = new Command("migrate");

migrateCommand
  .description("Migrate GAS project to open source")
  .argument("<script-id>", "Google Apps Script ID")
  .option("-o, --output <directory>", "Output directory", "./migrated-project")
  .option("-f, --frameworks <frameworks>", "Frameworks (guapo,genio,chiew)", "guapo,genio,chiew")
  .option("-d, --database <type>", "Database type (postgres,mysql,sqlite)", "postgres")
  .option("--expo", "Generate Expo mobile app alongside web app")
  .option("--mobile-only", "Generate only mobile app (no web)")
  .option("--demo", "Run in demo mode (no Google API calls)")
  .option("--analyze-only", "Only analyze, don't migrate")
  .action(async (scriptId, options) => {
    const spinner = ora(chalk.blue("ðŸš€ Starting CÂ³X migration engine...")).start();
    
    try {
      console.log(chalk.cyan("\n" + "=".repeat(50)));
      console.log(chalk.cyan("           CÂ³X MIGRATION ENGINE"));
      console.log(chalk.cyan("       3x Productivity Guaranteed"));
      console.log(chalk.cyan("=".repeat(50) + "\n"));
      
      console.log(chalk.yellow("ðŸ“‹ Migration Parameters:"));
      console.log(chalk.gray(`  Script ID: ${chalk.white(scriptId)}`));
      console.log(chalk.gray(`  Output: ${chalk.white(options.output)}`));
      console.log(chalk.gray(`  Frameworks: ${chalk.white(options.frameworks)}`));
      console.log(chalk.gray(`  Database: ${chalk.white(options.database)}`));
      console.log(chalk.gray(`  Demo Mode: ${chalk.white(options.demo ? "Yes" : "No")}`));
      console.log("");
      
      // Initialize OAuth client
      const oauthClient = new OAuthClient();
      const initialized = await oauthClient.initialize(options.demo);
      
      if (!initialized && !options.demo) {
        spinner.stop();
        console.log(chalk.yellow("âš ï¸  Authentication required."));
        console.log(chalk.cyan("Please run: c3x auth login"));
        return;
      }
      
      spinner.succeed(chalk.green("âœ… Authentication successful"));
      
      // Initialize conversion engine
      // eslint-disable-next-line no-unused-vars
      const converterEngine = new ConverterEngine(); // eslint-disable-line no-unused-vars
      // eslint-disable-next-line no-unused-vars
      const gasParser = new GasParser(); // eslint-disable-line no-unused-vars
      
      // Demo conversion (in real mode, this would parse actual GAS files)
      if (options.demo) {
        console.log(chalk.cyan("\nðŸ”§ Conversion Progress:"));
        
        // Demo GUAPO conversion
        console.log(chalk.green("  âœ… Converting APIs (GUAPO â†’ Express.js)"));
        await new Promise(resolve => setTimeout(resolve, 800));
        
        // Demo GENIO conversion
        console.log(chalk.green("  âœ… Converting automations (GENIO â†’ Bull queues)"));
        await new Promise(resolve => setTimeout(resolve, 800));
        
        // Demo CHIEW conversion
        console.log(chalk.green("  âœ… Converting UI (CHIEW â†’ React)"));
        await new Promise(resolve => setTimeout(resolve, 800));
      } else {
        // TODO: Real conversion logic
        console.log(chalk.cyan("\nðŸ”§ Real conversion would happen here"));
        console.log(chalk.gray("  1. Parse GAS files with GasParser"));
        console.log(chalk.gray("  2. Convert with ConverterEngine"));
        console.log(chalk.gray("  3. Generate modern code"));
      }
      
      // Generate project structure
      spinner.start(chalk.blue("ðŸ—ï¸ Generating project structure..."));
      
      const frameworks = options.frameworks.split(",");
      
      // Generate web project (unless mobile-only)
      if (!options.mobileOnly) {
        await generateProjectStructure(options.output, frameworks, { demo: options.demo });
      }
      
      // Generate mobile project (if expo flag is set)
      if (options.expo || options.mobileOnly) {
        const mobileOutput = options.mobileOnly ? options.output : `${options.output}-mobile`;
        await generateExpoProjectStructure(mobileOutput, frameworks, { 
          demo: options.demo,
          apiUrl: "http://localhost:3000",
        });
      }
      
      spinner.succeed(chalk.green("âœ… Project structure generated"));
      
      // Generate migration report
      spinner.start(chalk.blue("ðŸ“„ Generating migration report..."));
      await generateMigrationReport(options.output, { demo: options.demo, scriptId }, {});
      spinner.succeed(chalk.green("âœ… Migration report generated"));
      
      console.log(chalk.green("\nðŸŽ‰ Migration completed successfully!\n"));
      console.log(chalk.yellow("ðŸ“ Output:"), chalk.white(options.output));
      
      if (options.demo) {
        console.log(chalk.cyan("\nðŸ’¡ This was a demo. For real migration:"));
        console.log(chalk.white("   1. Set up Google OAuth: c3x auth setup"));
        console.log(chalk.white("   2. Login: c3x auth login"));
        console.log(chalk.white("   3. Run migration with real GAS ID"));
      }
      
      console.log(chalk.cyan("\nðŸš€ Next steps:"));
      console.log(chalk.white(`   1. cd ${options.output}`));
      console.log(chalk.white("   2. npm install"));
      console.log(chalk.white("   3. docker-compose up -d"));
      console.log(chalk.white("   4. npm run dev"));
      
    } catch (error) {
      spinner.fail(chalk.red("âŒ Migration failed"));
      console.error(chalk.red(`Error: ${error.message}`));
      console.log(chalk.gray("\nFor help: c3x migrate --help"));
      process.exit(1);
    }
  });

export default migrateCommand;


